#!/bin/ksh

f_mpv () { mpv --no-input-default-bindings "$1" & disown; }

alias ls="ls --color=auto"
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"

alias cm_stat="cmus-remote -C status"
alias cm_start="cmus-remote -C player-play"
alias cm_play="cmus-remote -p"
alias cm_pause="cmus-remote -u"
alias cm_prev="cmus-remote -r"
alias cm_next="cmus-remote -n"

alias ytfzf="ytfzf -D"

alias s_xi="doas xbps-install"
alias s_xr="doas xbps-remove"
alias s_xq="doas xbps-query"
alias s_xi_snf="s_xi --repository hostdir/binpkgs/nonfree"
alias s_xi_s="s_xi --repository hostdir/binpkgs"

alias s_v="doas vis"

alias s_r="doas reboot"
alias s_p="doas poweroff"

alias g_dot="git --git-dir=$XDG_CONFIG_HOME/dotfiles/ --work-tree=$HOME"
