#!/bin/ksh

HISTFILE="$HOME"/.local/cache/ksh_hist
HISTSIZE=500

P="\033["
KNRM="${P}0m"
KRED="${P}1;31m"
KGRN="${P}1;32m"
KYEL="${P}1;33m"
KBLU="${P}1;34m"
KMAG="${P}1;35m"
KCYN="${P}1;36m"
KWHT="${P}1;37m"

PS1="$(printf "╦═ %b${USER}%b@%b$(hostname) \
%b\${PWD}%b\n╚═══> " "$KMAG" "$KNRM" "$KGRN" "$KMAG" "$KNRM")"

. "$HOME"/.config/shell/profile
. "$HOME"/.config/shell/aliasrc

if [ -z "$DISPLAY" ] && [ "$(tty)" = /dev/tty1 ]; then
    exec startx "$XDG_CONFIG_HOME"/x11/xinitrc
fi

#if [ -z "$(tmux list-sessions | grep "$(whoami)")" ]; then
#    tmux new-session -s "$(whoami)" -d
#fi
#
#if [ "$TERM" != screen ]; then
#    exec tmux attach-session -t "$(whoami)"
#fi
