#!/bin/ksh

HISTFILE="$HOME"/.local/cache/ksh_hist
HISTSIZE=500

BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
POWDER_BLUE=$(tput setaf 153)
BLUE=$(tput setaf 4)
MAGENTA=$(tput setaf 5)
CYAN=$(tput setaf 6)
WHITE=$(tput setaf 7)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
BLINK=$(tput blink)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

export VISUAL="vi"
export EDITOR="vsi"

PS1="$(printf '╦═ ${RED}${USER}${NORMAL}@${BLUE}$(hostname) \
${NORMAL}${PWD}')\n╚═══> "

. "$HOME"/.config/shell/profile
. "$HOME"/.config/shell/aliasrc

if [ -z "${DISPLAY}" ] && [ "$(tty)" = "/dev/tty1" ]; then
	exec startx "$HOME/.config/x11/xinitrc"
fi
