#!/bin/sh

# dbus session
#if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
#    eval `dbus-launch --sh-syntax --exit-with-session`
#fi

# set runtime dir
unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXXXXXXXXX)

# set im method
#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
#export XMODIFIERS=@im=fcitx

mpd &

emacs --fg-daemon &

transmission-daemon &

xrdb -merge "$XDG_CONFIG_HOME"/x11/xresources

xsetroot -solid black &
xet -s off &

setxkbmap -layout us,ru -option -option grp:win_space_toggle &

exec xterm -name termbar -class termbar -T termbar -e "$HOME"/.local/bin/my_scripts/termbar &
exec bspwm
