#!/bin/sh

# dbus session
#if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
#    eval `dbus-launch --sh-syntax --exit-with-session`
#fi

# set runtime dir
unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=$(mktemp -d /tmp/$(id -u)-runtime-dir.XXXXXXXXXX)

# set im method
#export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
#export XMODIFIERS=@im=fcitx
export XMODIFIERS=@im=exwm-xim
export GTK_IM_MODULE=xim
export CLUTTER_IM_MODULE=xim

emacs --daemon &
mpd --kill; mpd &

xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"

exec bspwm
