#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

_monitor_connected () { ! [ -z "$(xrandr | grep "$1 connected")" ]; }

if _monitor_connected "HDMI-1" && _monitor_connected "DVI-I-1"; then
    xrandr --output HDMI-1 --mode 1920x1080 --rate 60.0*+ --primary \
	   --brightness 1.0 --gamma 0.76:0.75:0.68 \
	   --output DVI-I-1 --mode 1920x1080 --rate 60.0*+ --right-of HDMI-1 --rotate left \
	   --brightness 1.0 --gamma 0.76:0.75:0.68

    bspc monitor HDMI-1  -d I III V
    bspc monitor DVI-I-1 -d II IV
fi

bspc display -f I

bspc config border_width 3
bspc config window_gap   0
bspc config top_padding 27

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Firefox state=tiled
bspc rule -a termbar state=floating manage=off


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
